package org.lsj.gs.mathBoardGtr.config.entity.playGameField;

// 遊戲房間定義
public class ConstPlayGameField {
    public enum PlayGameFieldResource {
        R001_LUCKY777_NORMAL,

        R105_HHDZ_JAVA_NORMAL,
        R109_BJL_JAVA_NORMAL,
        R110_BRNN_JAVA_NORMAL,
        R111_LHD_JAVA_NORMAL,
        R112_ZJH_JAVA_NORMAL,
        R113_QZNN_JAVA_NORMAL,
        R113_QZNN_JAVA_HIGH_MIN_NORMAL,
        R113_QZNN_JAVA_TIMEOUT,
        R114_EBG_JAVA_NORMAL,
        R115_QZNN_KSZ_JAVA_NORMAL,
        R115_QZNN_KSZ_JAVA_TIMEOUT,
        R117_SG_JAVA_NORMAL,
        R122_QZPJ_JAVA_NORMAL,
        R125_TBNN_JAVA_NORMAL,
        R126_QZNN_K4Z_JAVA_NORMAL,
        R127_LZNN_JAVA_NORMAL,
        R129_MYBJL_JAVA_NORMAL,
        R132_CJNN_JAVA_NORMAL,

        R201_JCBY_JAVA_ONE_TARGET,
        R201_JCBY_JAVA_RANDOM_TARGET,
        R202_CSBY_JAVA_RANDOM_TARGET,
        R203_SLBY_JAVA_RANDOM_TARGET,
        R204_RYCS_JAVA_RANDOM_TARGET,
        R205_SZZB_JAVA_RANDOM_TARGET,

        R301_PXKY_JAVA_NORMAL,
        R302_DYDB_JAVA_NORMAL,
        R303_SDZW_JAVA_NORMAL,
        R304_WL_JAVA_NORMAL,
        R305_MJWS_JAVA_NORMAL,
        R306_BSZX_JAVA_NORMAL,
        R307_CCC_JAVA_NORMAL,
        R308_SBXC_JAVA_NORMAL,
        R309_SN_JAVA_NORMAL,
        R310_SWZS_JAVA_NORMAL,
        R311_LMJJC_JAVA_NORMAL,
        R312_DGRY_JAVA_NORMAL,
        R313_LLL_JAVA_NORMAL,
        R314_OLLDBZ_JAVA_NORMAL,
        R315_HJXB_JAVA_NORMAL,
        R316_XZCQ_JAVA_NORMAL,
        R320_CJWP_JAVA_NORMAL,
        R323_XJTB_JAVA_NORMAL,
        R324_ZCJZ_JAVA_NORMAL,

        R982_DEVELOP_BY_JAVA_RANDOM_TARGET,
        R983_DEVELOP_HJ_JAVA_NORMAL,
        R992_MODEL_BY_JAVA_RANDOM_TARGET,
        R993_MODEL_HJ_JAVA_NORMAL
    }
}
